### ISSUE TITLE
Israel CoA problem

### ISSUE THREAD

**Issue by hmlendea** [hmlendea/ck2-hip-mcn#19]
From Steam:

**pinkhyori** :
hi just a heads up. the latest 5th Nov update causes Israel's CoA to switch to some green/blue shield instead of its original blue menorah on a white background

**Comment by TheDovahkiin97** [comment]
working for me. the guy probably messed around with other files and should delete everything in ``Documents\Paradox Interactive\Crusader Kings II\HIP\gfx`` once
