### ISSUE TITLE
c_siracusa shouldn't be Syracuse

### ISSUE THREAD

**Issue by Lewa263** [hmlendea/ck2-hip-mcn#20]
The county c_siracusa is actually Paterno in the SWMH localization (which is more geographically accurate). You have a list of cultural names for Syracuse under c_siracusa, but they should be moved to b_syracuse and maybe c_modica (the county that contains b_syracuse).

**Comment by Lewa263** [comment]
Hmm, it looks like nearly every county in d_sicily is named after a barony in a separate county. You also have a name for Trapani in c_trapani, but c_trapani is Enna instead of Trapani.

**Comment by TheDovahkiin97** [comment]
those are the greek names and they are correct. example: ``After the Norman conquest in the 1040s, it was renamed Paternionis and began a period of flourishing``

**Comment by Lewa263** [comment]
You have completely missed what I was trying to say. I am pointing out errors that can be corrected in this mod, not arguing history.

The county that SWMH labels as "c_siracusa" is NOT the county of Syracuse/Siracusa. It is Paterno/Paternionis/Batarnù/etc. This MCN mod includes localization for that county such as `italian = "Siracusa"` and `roman = "Syracusae"`. This is what I am trying to point out as incorrect. Those names are historical and using them is fine, but NOT for c_siracusa. You would want to use those for c_modica, because that county contains the city of Syracuse/Siracusa. This mod already has `crimean_gothic = "Syrakousai" # Historical? Copied from Greek` under c_modica correctly, it is just all the other cultural localizations that are incorrectly placed under c_siracusa.

Similarly, this mod has a line `roman = "Drepanum` under the county that SWMH labels as c_trapani. However, c_trapani is not the county of Trapani. The actual Trapani is a barony in c_palermo, and I can see no evidence that the central province of Sicily was ever named anything related to Drepanum.

As I noted in my follow-up post, the Sicilian provinces are all badly named in SWMH (obviously not the fault of this mod). There are six provinces on the island of Sicily: c_palermo, c_messina, c_siracusa, c_modica, c_agrigento, and c_trapani. Their default names in SWMH are in the same order Palermo, Geraci, Paterno, Modica, Butera, and Aderno. You can see that few match the scripted c_ name. It's even worse, though. While c_palermo contains b_palermo, c_modica contains b_modica, and c_agrigento contains b_girgenti (equivalent names in different languages), the other three counties DO NOT contain the baronies corresponding to their scripted names! b_messina is in c_siracusa, b_syracusa is in c_modica, and b_trapani is in c_palermo. It's clear that the SWMH map of Sicily changed a lot between the setting of the county script names and the current distribution of holdings.

But the reason I wrote this up is that the MCN mod fails to account for these discrepancies. you have cultural names listed that match with the script names like c_siracusa and c_trapani instead of the intended names of these provinces. The research that went into finding other names for Syracusa and Trapani aren't wasted, because they can still be applied to the baronies with those names. However, those baronies are not even in the similarly-named counties.
